plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

service: recuerda

provider:
  name: aws
  runtime: python3.6

  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

# you can overwrite defaults here
  stage: dev
  region: eu-west-1

package:
#  include:
#    - include-me.py
#    - include-me-dir/**
  exclude:
    - venv/**      
    - src/**      

functions:
  auth:
      runtime: nodejs4.3
      handler: auth.authorize

  search:
    runtime: python3.6
    handler: handler.search
    events:
      - http:
          path: search/{src}/{dest}/{query}
          method: get
          authorizer: auth
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
  list:
    runtime: python3.6
    handler: handler.list
    events:
      - http:
          path: list
          method: get
          authorizer: auth
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token

resources:
  Resources:
    RecuerdaDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: query
            AttributeType: S
        KeySchema:
          -
            AttributeName: query
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
