plugins:
  - serverless-python-requirements
  - serverless-s3-sync
custom:
  pythonRequirements:
    dockerizePip: true

service: recuerda

provider:
  name: aws
  runtime: python3.6

  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

# you can overwrite defaults here
  stage: dev
  region: eu-west-1

package:
#  include:
#    - include-me.py
#    - include-me-dir/**
  exclude:
    - venv/**      
    - src/**      

functions:
  auth:
      runtime: nodejs4.3
      handler: auth.authorize

  search:
    runtime: python3.6
    handler: handler.search
    events:
      - http:
          path: search/{src}/{dest}/{query}
          method: get
          authorizer: auth
          cors: true
  list:
    runtime: python3.6
    handler: handler.list
    events:
      - http:
          path: list
          method: get
          authorizer: auth
          cors: true
  addMemo:
    runtime: python3.6
    handler: handler.add_memo
    events:
    - http:
        path: addMemo
        method: post
        authorizer: auth
        cors: true
  postTraining:
    runtime: python3.6
    handler: handler.post_training
    events:
    - http:
        path: train
        method: post
        authorizer: auth
        cors: true
  tags:
    runtime: python3.6
    handler: handler.tags
    events:
    - http:
        path: tags
        method: get
        authorizer: auth
        cors: true
  me:
    runtime: python3.6
    handler: handler.me
    events:
    - http:
        path: me
        method: get
        authorizer: auth
        cors: true

resources:
  Resources:
    RecuerdaDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: front
            AttributeType: S
        KeySchema:
          -
            AttributeName: front
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
